---
abstract: 'Perl extension to generate cryptographically-secure'
author:
  - 'David Oswald <davido@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bytes-Random-Secure
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::Random::Source: 0
  MIME::Base64: 0
  MIME::QuotedPrint: 0
  Math::Random::ISAAC: 0
  Test::More: 0
version: 0.05
