---
abstract: 'Perl extension to generate cryptographically-secure random bytes.'
author:
  - 'David Oswald <davido@cpan.org>'
build_requires:
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '6.56'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bytes-Random-Secure
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Crypt::Random::Seed: '0'
  MIME::Base64: '0'
  MIME::QuotedPrint: '3.03'
  Math::Random::ISAAC: '0'
  Scalar::Util: '1.21'
  perl: '5.006000'
resources:
  Metaspec:
    version: 2
version: '0.29'
